project:
  type: website
  output-dir: docs
  resources:
    - "rendered/**"

website:
  title: "portfolio_website"
  open-graph: true

  navbar:
    title: "Amir Alnajjar"
    pinned: true
    background: "#ffffff"
    foreground: "#111111"
    left:
      - text: "Data Science"
        menu:
          - text: "Data Visualization"
            href: data-viz.qmd
          - text: "Data Wrangling"
            href: data-wrangling.qmd
          - text: "R Data Types"
            href: data-types.qmd
          - text: "Advanced R Programming"
            href: r-programming.qmd
          - text: "Cloud Analytics"
            href: cloud-analytics.qmd
    tools:
      - icon: github
        href: https://github.com

  sidebar:
    #style: "floating"
    collapse-level: 1
    search: true
    pinned: false
    background: "#ffffff"

    contents:
        - href: index.qmd
          text: Home
        - about.qmd
        - coursework.qmd
        - certifications.qmd
        - href: presentations.qmd
          text: Revealjs Presentations
        - section: "Data Science Projects"
          contents:
            - data-viz.qmd
            - data-wrangling.qmd
            - data-types.qmd
            - r-programming.qmd
            - cloud-analytics.qmd
        - digital-marketing.qmd
        - google-analytics.qmd
        - projects.qmd
        - dashboard.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    smooth-scroll: true

    fontsize: 1.05rem
    linestretch: 1.7

    backgroundcolor: "#f8f9fb"
    fontcolor: "#1a1a1a"
    linkcolor: "#3a3a3a"

    mainfont: "Inter"

editor: visual


       

