---
title: "M07-2-Application Assignment for R Data Types"
author: "Alnajjar Amir"
date: '`r format(Sys.time())`'
format: 
  html: 
    theme: cosmo
    toc: true
    toc-location: right-body
    toc_depth: 4
    code-fold: false
    code-line-numbers: true
    code-link: true
    number-sections: true
    embed-resources: true
    df-print: paged
execute: 
  freeze: auto
  echo: fenced
  warning: false
  error: true
---

## Question 1

```{r}

# Q1.1 
stock_prices <- c(42.5, 43.0, 44.1, 2.7) 
class(stock_prices)

#1.2 
stock_company <- c("Microsoft", "Apple", "Facebook", "Tesla") 

stock_company

#1.3 
stock_ticker <- c("MSFT", "AAPL", "FB", "TSLA")

class(stock_ticker)

#1.4 
make_cars <- c(FALSE, FALSE, FALSE, TRUE) 

make_cars

#1.5 
stock_prices <- stock_prices + 5 

stock_prices

#1.6 

names(stock_prices) <- stock_company 

stock_prices
```

## Question 2

```{r}

#2.1
stock_info.df <- data.frame(
  stock_prices,
  stock_company,
  stock_ticker,
  make_cars
)

dim(stock_info.df)
summary(stock_info.df)

#2.2
stock_info.df$stock_prices[stock_info.df$stock_company == "Tesla"] <- 47.7
stock_info.df

```

### Question 3

```{r}

#3.1 

new_row <- data.frame( stock_prices = 50.4, 
                       stock_company = "General Motors", 
                       stock_ticker = "GM", make_cars = TRUE
                       ) 
stock_info.df <- rbind(stock_info.df, new_row) 

rownames(stock_info.df)[nrow(stock_info.df)] <- "General Motors" 

stock_info.df 

#3.2 

stock_info.df$open_price <- c(47.3, 47.8, 49.5, 47.9, 55.3) 

stock_info.df
```

### Question 4

```{r}

#4.1 

stock_info.df$change_stock_prices_percent <- (stock_info.df$stock_prices - stock_info.df$open_price) / stock_info.df$open_price * 100 
stock_info.df 

#4.2 

subset(stock_info.df, change_stock_prices_percent > 0)

subset(stock_info.df, change_stock_prices_percent < 0)
```

### Question 5

```{r}

# Base R
odd.mat <- matrix(seq(1, by = 2, length.out = 50), nrow = 5, ncol = 10)
odd.mat

# Tidyverse
library(tidyverse)

odd.mat2 <- seq(1, by = 2, length.out = 50) %>%
  matrix(nrow = 5, ncol = 10)

odd.mat2
```

### Question 6

```{r}

library(stringr)

# First word extraction
first_words <- word(sentences, 1)

# First 20 words
first_words[1:20]

# Count "The"
count_the <- sum(first_words == "The")
count_the

# Proportion
prop_the <- count_the / length(first_words)
prop_the

# One pipeline 
sentences %>% word(1) %>% (\(x) sum(x == "The")) 

sentences %>% word(1) %>% (\(x) sum(x == "The") / length(x))
```

### Question 7

```{r}
install.packages("Lahman")

library(Lahman)
library(dplyr)
library(ggplot2)

name_counts <- People %>%
  filter(nameFirst %in% c("John", "Joe")) %>%
  count(nameFirst)

name_counts

ggplot(name_counts, aes(x = nameFirst, y = n)) +
  geom_col() +
  labs(title = "Count of John and Joe",
       x = "Name",
       y = "Count")
```

### Question 8

```{r}

library(gapminder)
library(forcats)

#8.1
levels(gapminder$continent)

pop_2007 <- gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total_pop = sum(pop))

pop_2007

pop_2007 %>%
  arrange(desc(total_pop))

gapminder1 <- gapminder %>%
  mutate(continent = fct_reorder(continent, pop, .fun = sum, .desc = TRUE))

levels(gapminder1$continent)
#8.2
gapminder %>%
  filter(year == 2007) %>%
  group_by(continent) %>%
  summarise(total_pop = sum(pop)) %>%
  ggplot(aes(x = reorder(continent, -total_pop), y = total_pop)) +
  geom_col() +
  labs(title = "Population by Continent (2007)",
       x = "Continent",
       y = "Population")
```

### Question 9

```{r}

library(patchwork)

#9.1
asia_2007 <- gapminder %>%
  filter(year == 2007, continent == "Asia")

nrow(asia_2007)

#9.3 Top 5
top5 <- asia_2007 %>%
  slice_max(lifeExp, n = 5)

p1 <- ggplot(top5, aes(x = reorder(country, lifeExp), y = lifeExp)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 5 Life Expectancy")

#9.4 Bottom 5
bottom5 <- asia_2007 %>%
  slice_min(lifeExp, n = 5)

p2 <- ggplot(bottom5, aes(x = reorder(country, lifeExp), y = lifeExp)) +
  geom_col() +
  coord_flip() +
  labs(title = "Bottom 5 Life Expectancy")

p1 + p2
```

### Question 10

```{r}

library(nycflights13)
library(lubridate)

#10.1
str(flights)

#10.2
flights_lub <- flights %>%
  filter(!is.na(dep_time), !is.na(arr_time), !is.na(air_time)) %>%
  mutate(
    dep_time = make_datetime(year, month, day, dep_time %/% 100, dep_time %% 100),
    arr_time = make_datetime(year, month, day, arr_time %/% 100, arr_time %% 100)
  ) %>%
  select(origin, dest, air_time, starts_with("dep"), starts_with("arr"))

#10.3
flights_lub %>%
  count(date = as.Date(dep_time)) %>%
  ggplot(aes(x = date, y = n)) +
  geom_line() +
  labs(title = "Daily Flights in 2013")

#10.4
flights_lub %>%
  filter(month(dep_time) == 7, day(dep_time) == 4) %>%
  count(hour(dep_time)) %>%
  ggplot(aes(x = `hour(dep_time)`, y = n)) +
  geom_col() +
  labs(title = "Flights on July 4")

#10.5
flights_lub %>%
  mutate(travel_time = arr_time - dep_time) %>%
  arrange(travel_time)

#10.6 Fix overnight
flights_lub <- flights_lub %>%
  mutate(
    arr_time = if_else(arr_time < dep_time, arr_time + days(1), arr_time),
    travel_time = as.numeric(arr_time - dep_time)
  )

summary(flights_lub$travel_time)

#10.7
flights_lub %>%
  filter(month(dep_time) == 7, day(dep_time) == 4) %>%
  ggplot(aes(x = air_time, y = travel_time)) +
  geom_point() +
  labs(title = "Travel vs Air Time")
```
